---
channel: stable
addons:
   node-red:
    repository: hassio-addons/addon-node-red
    target: node-red
    image: hassioaddons/node-red-{arch}
  nginxproxymanager:
    repository: averstappen/addon-nginx-proxy-manager
    target: proxy-manager
    image: hassioaddons/nginxproxymanager-{arch}
    
